---
# "Step 0" - runs every push / PR
# ref: https://jupyter-releaser.readthedocs.io/en/latest/how_to_guides/convert_repo_from_repo.html
name: Check

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

permissions: {}

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo 🛒
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set Up Python 🐍
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x

      - name: Install pre-commit 📦
        run: |
          pip install --upgrade pip
          pip install --upgrade pre-commit

      - name: Run pre-commit hooks ✅
        run: pre-commit run --all-files

  # verifies compatibility and release-ability
  # uses dry-run mode; does not make PRs or push changes
  check_release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Base Setup
        uses: ./.github/actions/setup
        with:
          release-toolchain: 'true'

      - name: Install Dependencies
        run: uv pip install --no-build-isolation --no-deps --editable .

      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@70e58c50c736ad496cca11fe4f2446033b68b027 # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Distributions
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jupyterlab_material_night_eighties-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
